# EEEL 4220 HW7
## Fall 2022

### Problem 1 Two-bus Power Flow (20)

Consider the following two-bus system in which a generator powers the demand through three transmission lines. Calculate the line flow through each line. 

Hint: use the DC power flow equation as your starting point, note that each line has a different power flow and reactance, but shares the same angle variable.

<div>
<center><img src="https://ningkunzheng.github.io/images/hws/hw7_fig1.png" width="800"/></center>
</div>

In [ ]:
#Kirchoff's Current Law states: I = I1 + I2 + I3
#Kirchoff's Voltage Law states: V1 = V2 = V3
#Voltage = I * R (current * resistance) 
D = 200
X1 = 0.1 
X2 = 0.3
X3 = 0.2
F1 = X2 * X3 / ( X1 * X2 + X1 * X3 + X2 * X3 ) * D
F2 = X1 * X3 / ( X1 * X2 + X1 * X3 + X2 * X3 ) * D
F3 = X1 * X2 / ( X1 * X2 + X1 * X3 + X2 * X3 ) * D
print("The power through the transmission lines are: ", "Flow 1:", '%.2f' % F1, "Flow 2:", '%.2f' % F2, "Flow 3:", '%.2f' % F3)


The power through the transmission lines are:  Flow 1: 109.09 Flow 2: 36.36 Flow 3: 54.55


### Problem 2 Two-bus Economic Dispatch (20)

Consider the system in Figure 1 with three lines and the listed reactance, but now there are generators at both buses:
* Bus 1 (left one) - Has Generator 1 with a production cost curve of $C(p) = 0.01p^2 + 20p + 100$, and the demand is 100 MW
* Bus 2 (right one) - Has Generator 2 with a production cost curve of $C(p) = 0.02p^2 + 30p + 100$, and the demand is 200 MW

Now assume Line one ($X_1 = 0.1$ p.u.) has a flow limit of 30 MW, solve the optimal economic dispatch and calculate

1. The generation output of Generator 1 and 2. (10)
2. The marginal price at Bus 1 and 2. (5)
3. The total congestion surplus. (5)


In [ ]:
print("Question 1:")
P1 = 6/11*200
print("The output from generator 1 is", '%.2f' % P1, "which is higher than the given limit")
P2 = (P1 - 30)/(6/11)
print("The output from generator 2 is", '%.2f' % P2)
P1 = 300 - P2
print("Therefore since P1 + P2 = 300, P1 will be:,", '%.2f' % P1, "and P2 is", '%.2f' % P2) 


print("Question 2:")
#Find marginal cost of PT (derr C1 and C2)
#plug 30 in both derr as the value for p 
def DC1(p):
    return 0.02 * p + 20
def DC2(p):
    return 0.04 * p + 30
print("MF for bus 1 is:", DC1(155))
print("MF for bus 2 is:", DC2(145))

print("Question 3:")
F12 = 300 - P1
surplus = (DC2(145) - DC1(155)) * 55 
print("The total congestion surplus is:", '%.2f' %  surplus)

Question 1:
The output from generator 1 is 109.09 which is higher than the given limit
The output from generator 2 is 145.00
Therefore since P1 + P2 = 300, P1 will be:, 155.00 and P2 is 145.00
Question 2:
MF for bus 1 is: 23.1
MF for bus 2 is: 35.8
Question 3:
The total congestion surplus is: 698.50


### Problem 3 3-Bus Power Flow (30)

Consider the power system shown in the figure. Assuming that the only limitations imposed by the network are imposed by the thermal capacity of the transmission lines and that reactive power flows are negligible, **check** that the sets of transactions shown in the table are simultaneously feasible.

Hint: You need to apply super-position in this case tring to decompose the three bus power flow into the combination of parallel path flows each with one source and one sink.

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-73oq{border-color:#000000;text-align:left;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 435px">
<colgroup>
<col style="width: 138px">
<col style="width: 91px">
<col style="width: 100px">
<col style="width: 106px">
</colgroup>
<thead>
  <tr>
    <th class="tg-73oq" rowspan="2"></th>
    <th class="tg-73oq" rowspan="2">Seller</th>
    <th class="tg-73oq" rowspan="2">Buyer</th>
    <th class="tg-73oq" rowspan="2">Amount</th>
  </tr>
  <tr>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-73oq" rowspan="3">Set 1<br></td>
    <td class="tg-73oq">B</td>
    <td class="tg-73oq">X</td>
    <td class="tg-73oq">200</td>
  </tr>
  <tr>
    <td class="tg-73oq">A</td>
    <td class="tg-73oq">Z</td>
    <td class="tg-73oq">400</td>
  </tr>
  <tr>
    <td class="tg-73oq">C</td>
    <td class="tg-73oq">Y</td>
    <td class="tg-73oq">300</td>
  </tr>
  <tr>
    <td class="tg-73oq" rowspan="5">Set 2</td>
    <td class="tg-73oq">B</td>
    <td class="tg-73oq">Z</td>
    <td class="tg-73oq">600</td>
  </tr>
  <tr>
    <td class="tg-73oq">A</td>
    <td class="tg-73oq">X</td>
    <td class="tg-73oq">300</td>
  </tr>
  <tr>
    <td class="tg-73oq">A</td>
    <td class="tg-73oq">Y</td>
    <td class="tg-73oq">200</td>
  </tr>
  <tr>
    <td class="tg-73oq">A</td>
    <td class="tg-73oq">Z</td>
    <td class="tg-73oq">200</td>
  </tr>
  <tr>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-73oq" rowspan="5">Set 3</td>
    <td class="tg-73oq">C</td>
    <td class="tg-73oq">X</td>
    <td class="tg-73oq">1000</td>
  </tr>
  <tr>
    <td class="tg-73oq">X</td>
    <td class="tg-73oq">Y</td>
    <td class="tg-73oq">400</td>
  </tr>
  <tr>
    <td class="tg-73oq">B</td>
    <td class="tg-73oq">C</td>
    <td class="tg-73oq">300</td>
  </tr>
  <tr>
    <td class="tg-73oq">A</td>
    <td class="tg-73oq">C</td>
    <td class="tg-73oq">200</td>
  </tr>
  <tr>
    <td class="tg-73oq">A</td>
    <td class="tg-73oq">Z</td>
    <td class="tg-73oq">100</td>
  </tr>
</tbody>
</table>


</br>
</br>
</br>

<div>
<center><img src="https://ningkunzheng.github.io/images/hws/hw7_fig2.png" width="500"/></center>
</div>

In [ ]:
import numpy as np
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

print("Verify the feasibility of each set of transactions")
print("SET 1")
print("Demand: B = 200MW, Y = 300MW, A = 400MW, and X = 200MW")

A = np.array([[1, 1, 0],
              [-1, 0, 1],
              [0.2, -0.4, 0.4]])

Arev = np.linalg.inv(A)
B = np.array([[-100], [200], [0]])
set1 = np.dot(Arev, B)
print("The values for F12, F13, and F23 are the following, respectively:")
print(set1)

print("SET 2")
print("Demand: B = 600MW, Y = 200MW, A = 700MW, X = 300MW")

B2 = np.array([[400], [400], [0]])
set2 = np.dot(Arev, B2)
print("The values for F12, F13, and F23 are the following, respectively:")

print(set2)

print("SET 3")
print("Demand: B = 300MW, Y = 400MW, A = 300MW, X = 600MW")
B3 = np.array([[-100], [-100], [0]])
print("The values for F12, F13, and F23 are the following, respectively:")
set3 = Arev.dot(B3)
print(set3)



Verify the feasibility of each set of transactions
SET 1
Demand: B = 200MW, Y = 300MW, A = 400MW, and X = 200MW
The values for F12, F13, and F23 are the following, respectively:
[[-120.]
 [  20.]
 [  80.]]
SET 2
Demand: B = 600MW, Y = 200MW, A = 700MW, X = 300MW
The values for F12, F13, and F23 are the following, respectively:
[[  0.]
 [400.]
 [400.]]
SET 3
Demand: B = 300MW, Y = 400MW, A = 300MW, X = 600MW
The values for F12, F13, and F23 are the following, respectively:
[[  -0.]
 [-100.]
 [-100.]]


### Problem 4 Three-bus Economic Dispatch (30)

Consider the the three-bus power system shown in the figure. The system has three lines with **equivalent** reactance with unlimited flow limits. Solve the economic dispatch and calculate
1. Output of generator C.
2. Flow from Bus 1 to Bus 2.
3. The nodel marginal price at Bus 2.

Hint: since there are no flow limits, solve the economic dispatch first without considering power flow, then calculate the power flow using the dispatch result.

</br>
<div>
<center><img src="https://ningkunzheng.github.io/images/hws/hw7_fig3.png" width="500"/></center>
</div>

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-73oq{border-color:#000000;text-align:left;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg" style="undefined;table-layout: fixed; width: 451px">
<colgroup>
<col style="width: 132px">
<col style="width: 135px">
<col style="width: 184px">
</colgroup>
<thead>
  <tr>
    <th class="tg-73oq" rowspan="2">Generator</th>
    <th class="tg-73oq" rowspan="2">Capacity (MW)</th>
    <th class="tg-73oq" rowspan="2">Marginal Cost ($/MW)</th>
  </tr>
  <tr>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-73oq">A</td>
    <td class="tg-73oq">150</td>
    <td class="tg-73oq">12</td>
  </tr>
  <tr>
    <td class="tg-73oq">B</td>
    <td class="tg-73oq">200</td>
    <td class="tg-73oq">15</td>
  </tr>
  <tr>
    <td class="tg-73oq">C</td>
    <td class="tg-73oq">150</td>
    <td class="tg-73oq">10</td>
  </tr>
  <tr>
    <td class="tg-0lax">D</td>
    <td class="tg-0lax">400</td>
    <td class="tg-0lax">8</td>
  </tr>
</tbody>
</table>

In [ ]:
print("Question 1:")
print("Our total is 400+40+80=520. The first cheapest marginal cost is D, for the leftover, 520-400=120 we will generate from C")
print("The output of generator C is 120 MW\n")

print("Question 2:")
A = 150
B = 200
C = 120
D = 400
print("The flow in 13 and 23 should be equal to C+D-40")
print("Flow 13+23 is equal to", C+D-40)
print("Flow 12 and 13 is equal to -400")
print("Flow 12 and 32 is equal to -80")
print("Using the Kirchoff's Voltage Law, flow 12 and 13 and 23 are equal to 0.")
#120 + 400 - 40 = -F13 - F23
#480 = -F13 - F23 
#-400 = F12 + F13
#-80 = -F12 + F23 
#F12 + F23 - F13 = 0
#after rearranging: 
F12 = -106.67
F23 = -186.67
F31 = -293.33
print("Therefore the flow from Bus 1 to 2 is", F12, "MW\n")

print("Question 3:")
print("The marginal cost for bus 2 is 10$/MW")

Question 1:
Our total is 400+40+80=520. The first cheapest marginal cost is D, for the leftover, 520-400=120 we will generate from C
The output of generator C is 120

Question 2:
The flow in 13 and 23 should be equal to C+D-40
Flow 13+23 is equal to 480
Flow 12 and 13 is equal to -400
Flow 12 and 32 is equal to -80
Using the Kirchoff's Voltage Law, flow 12 and 13 and 23 are equal to 0.
Therefore the flow from Bus 1 to 2 is -106.67 MW

Question 3:
The marginal cost for bus 2 is 10$/MW
